CREATE TABLE IF NOT EXISTS users (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    AUTHORIZATION VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
    UPDATED_AT DATETIME(3),
    DELETED_AT DATETIME(3),
    PRIMARY KEY(ID),
    unique (EMAIL, NAME)
);