CREATE TABLE IF NOT EXISTS users (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    AUTHORIZATION VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
    UPDATED_AT DATETIME(3),
    DELETED_AT DATETIME(3),
    PRIMARY KEY(ID),
    unique (EMAIL, NAME)
);

CREATE TABLE IF NOT EXISTS blogs (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USERS_ID BIGINT NOT NULL,
    TITLE VARCHAR(1000) NOT NULL,
    CONTENT TEXT NOT NULL,
    IMAGE_ID BIGINT NOT NULL,
    CREATED_AT DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
    UPDATED_AT DATETIME(3),
    DELETED_AT DATETIME(3),
    PRIMARY KEY(ID),
);